[package]
name = "bpho-computational-challenge-2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.2.2"
eframe = "0.22.0"
serde = { version = "1.0.164", features = ["derive"] }
